def get_teams ():
    teams=  ['Szeged', "Debrecen", "Kárpátalja", "Pécs", "Eger"]
    return teams

def get_gaze_csv_coluns ():
    csv_dict = {
"LPMM":"The left pupil diameter in millimeters.",
"LPMMV":"The left pupil diameter valid flag is 1 for valid and 0 for not valid.",
"RPMM":"The right pupil diameter in millimeters.",
"RPMMV":"The right pupil diameter valid flag is 1 for valid and 0 for not valid.",
"DIAL":"The position of the user dial (0 to 1).",
"DIALV":"The dial valid flag is 1 for valid (connected) and 0 for not valid.",
"GSR":"The galvanic skin response value (ohms).",
"GSRV":"The galvanic skin response valid flag is 1 for valid and 0 for not valid.",
"HR":"The heart rate value in beats per minute.",
"HRV":"The heart rate valid flag is 1 for valid (connected) and 0 for not valid.",
"HRP":"The heart rate pulse signal used to calculate the heart rate (unitless).",
"IBI":"The heart rate interbeat interval, time between heart beats (seconds).",
"TTL0":"The value of analog TTL0 channel (0 to 1024).",
"TTL1":"The value of digital TTL1 channel (0 or 1).",
"TTL2":"The value of digital TTL2 channel (0 or 1).",
"TTL3":"The value of digital TTL3 channel (0 or 1).",
"TTL4":"The value of digital TTL4 channel (0 or 1).",
"TTL5":"The value of digital TTL5 channel (0 or 1).",
"TTL6":"The value of digital TTL6 channel (0 or 1).",
"TTL6V":"The TTL valid flag is 1 for valid (connected) and 0 for not valid.",
"PIXS":"The conversion scale (pixels to mm) if a tracking marker is used.",
"PIXV":"The conversion scale valid flag is 1 for valid and 0 for not valid.",
"AOI":"AOI name if the current fixation point is within (overlapping AOIs are hyphenated).",
"SACCADE_MAG":"Saccade magnitude calculated as the distance between the current fixation and last fixation.",
"SACCADE_DIR":"Saccade direction calculated as the angle of the vector (current fixation - last fixation) from horizontal.",
"VID_FRAME":"For Video media items, the frame number of the video displayed when the data record was captured.",
"MEDIA_ID":"A unique numeric identifier associated with the media item in the media list.",
"MEDIA_NAME":"The user defined name of a media item.",
"WEB_ID":"A unique numeric identifier associated with the web page recorded.",
"WEB_TITLE":"The TITLE of the webpage from the webpage source (HTML).",
"WEB_URL":"The URL of the webpage.",
"CNT":"The COUNT increments once for each data record generated by Control.",
"TIME":"Time elapsed in seconds since the recording started.",
"TIMETICK":"CPU ticks recorded at time as TIME, can be used to synchronize data with other sources.",
"FPOGX":"The X-coordinate of the fixation POG, as a percentage of the screen width (0 to 1).",
"FPOGY":"The Y-coordinate of the fixation POG, as a percentage of the screen height (0 to 1).",
"FPOGS":"The starting time of the fixation POG in seconds since the system initialization or calibration.",
"FPOGD":"The duration of the fixation POG in seconds.",
"FPOGID":"The fixation POG ID number.",
"FPOGV":"The FPOG valid flag is 1 for valid and 0 for not valid.",
"BPOGX":"The X-coordinate of the un-filtered POG (left&right average), as a percentage of the screen width (0 to 1).",
"BPOGY":"The Y-coordinate of the un-filtered POG (left&right average), as a percentage of the screen height (0 to 1).",
"BPOGV":"The BPOG valid flag is 1 for valid and 0 for not valid.",
"CX":"The X-coordinate of the mouse cursor position, as a percentage of the screen width (0 to 1).",
"CY":"The Y-coordinate of the mouse cursor position, as a percentage of the screen height (0 to 1).",
"CS":"Mouse cursor state: 0 for steady state, 1 for left down, 2 for right down, 3 left up, 4 right up.",
"K":"The keyboard keystroke key value.",
"KBS":"The keyboard keystroke state (0=IDLE, 1=DOWN (pressed), 2=UP (released).",
"USER":"A custom data field that may be set by the user via the API or Remote.",
"LPCX":"The X-coordinate of the left eye pupil in the camera image, as a percentage of width (0 to 1).",
"LPCY":"The Y-coordinate of the left eye pupil in the camera image, as a percentage of height (0 to 1).",
"LPS":"The scale factor of the left eye pupil, normalized to 1 at the head depth at calibration.",
"LPV":"The left pupil valid flag is 1 for valid and 0 for not valid.",
"RPCX":"The X-coordinate of the right eye pupil in the camera image, as a percentage of width (0 to 1).",
"RPCY":"The Y-coordinate of the right eye pupil in the camera image, as a percentage of height (0 to 1).",
"RPD":"The diameter of the right eye pupil in pixels.",
"RPS":"The scale factor of the right eye pupil, normalized to 1 at the head depth at calibration.",
"RPV":"The right pupil valid flag is 1 for valid and 0 for not valid.",
"BKID":"A unique numeric identifier assigned to each blink. Equal to 0 when no blink is detected.",
"BKDUR":"The duration of the preceding blink in seconds.",
"BKPMIN":"The number of blinks in the previous 60 second period of time.",
    }
    return csv_dict

def get_gaze_calibrations (team:str):
    
    if team.lower() == "sszeged":
        return 60, 50
    else:
        return 0, 0